version: "3"
services:
  tax-calculator:
    build: .
    image: tax-calculator
    ports: 
      - 3000:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; node db_setup.js; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/shopee
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopee